# =============================================================================
# VALUES DEFINITION
# =============================================================================

---
gitlab:
  endpoint: "1"
  token: "1"
