# ==============================================================================
# TEMPLATE DEFAULT TAGS
# ==============================================================================

# AWS RUNNER DEVELOP
.default:tags-develop:
  tags:
    - devops-develop

# AWS RUNNER SANDBOX
.default:tags-sandbox:
  tags:
    - devops-sandbox

# AWS RUNNER STAGE
.default:tags-stage:
  tags:
    - devops-stage

# AWS RUNNER PROD
.default:tags-prod:
  tags:
    - devops-prod

# ==============================================================================
# TEMPLATE RETRY
# ==============================================================================

.default:retry:
  retry:
    max: 2  # This is confusing but this means "3 runs at max".
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure
      - job_execution_timeout
      - stuck_or_timeout_failure

.default:retry-always:
  retry:
    max: 2 # This is confusing but this means "3 runs at max".
    when:
      - always
      
# ==============================================================================
# TEMPLATE ONLY CHANGES
# ==============================================================================

# FEATURE
.only:changes-feature:
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_BRANCH =~ /^feature\//
  except:
    refs:
      - merge_requests

# DEVELOP
.only:changes-develop:
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_BRANCH == "develop"
  except:
    refs:
      - merge_requests

# SANDBOX
.only:changes-sandbox:
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_BRANCH == "sandbox"
  except:
    refs:
      - merge_requests

# STAGE
.only:changes-stage:
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_BRANCH == "stage"
  except:
    refs:
      - merge_requests

# MASTER
.only:changes-master:
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_BRANCH == "master"
  except:
    refs:
      - merge_requests

# ==============================================================================
# TEMPLATE USE
# ==============================================================================

.use-docker-in-docker:
  image: docker:${DOCKER_VERSION}
  services:
    - docker:${DOCKER_VERSION}-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_BUILDKIT: 1
